# Generated by Django 3.0.5 on 2020-05-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200510_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='summary',
            new_name='body',
        ),
    ]
